name: All Automated Tests (Manual Run)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_grep:
        description: >
          Filter tests (Regex)
          --------------------
          EMPTY: All tests
          '@smoke|@regression': Only specific tags
          '^[^@]*$': Tests without tags 
          '@smoke|^[^@]*$': tags + untagged tests
        required: false
        default: ''

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '24.x'
    - name: Install dependencies
      run: npm ci
    - name: Create Auth directory
      run: mkdir -p playwright/.auth
    - name: Install Playwright Browsers
      run: npx playwright install chrome --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project=full-run --grep "${{ github.event.inputs.test_grep }}"
      env:
        BASE_URL: ${{ vars.BASE_URL }}
        API_URL: ${{ vars.API_URL }}
        CUSTOMER_EMAIL: ${{ secrets.CUSTOMER_EMAIL }}
        CUSTOMER_PASSWORD: ${{ secrets.CUSTOMER_PASSWORD }}
        CUSTOMER_NAME: ${{ vars.CUSTOMER_NAME }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
